### PR TITLE
Add custom autocomplete

### PR DESCRIPTION
**Pull request by kefahB**
Hi @davecoffin,

I add the ability to use nativescript-filterable-listpicker as a autocomplete .. that add textChangeEvent to TextField and we can get data from backend server or like here from Google Place API

We can use it as originally and as autocomplete in the same instance by setting isAutocomlete to true

Excuse my english : I do not speak english for that I do not make a lot of comment on README.MD

### CODE REVIEW

**Comment by shiv19** [comment]
@kefahB 
Excellent work! well done :)

**Comment by kefahB** [comment]
Hi @shiv19, 

There is any advance on this PR ? I am thinking about image caching, because when we have à lot of items, images was slowly charged...

**Comment by shiv19** [comment]
@kefahB if I had access to merge, I would have merged it already. I don't have access to release this plugin to npm either.

@davecoffin please do the needful :)

**Comment by kefahB** [comment]
Thanks ;-)

**Comment by davecoffin** [comment]
@kefahB thanks for this, its been published. I cant test it though since I'm on nativescript 6 and the nativescript 6 version is now on proplugins, so make sure everything works and we will be good to go :)

**Pull request merged**
