### PR TITLE
Update filterable-listpicker.ts

### PR DESCRIPTION
**Pull request by shiv19**
parse() is deprecated use Builder.parse() instead

### CODE REVIEW

**Comment by shiv19** [comment]
⚠️
that is a breaking change. 6.2 and up only

**Comment by kefahB** [comment]
Hi @shiv19  and @davecoffin ,

First Happy new year :)

Dave can you please publish the last commit to npm package .. it is about the return status ont a `set` accessor `set isAutocomplete(val: boolean);`

Webpack block the CLI with those errors

````ts
ERROR in node_modules/nativescript-filterable-listpicker/index.d.ts(30,9):
TS1086: An accessor cannot be declared in an ambient context.

ERROR in node_modules/nativescript-filterable-listpicker/index.d.ts(31,9):
```

**Comment by davecoffin** [comment]
@shiv19 I dont know that this was ever updated to fully support {N} 6. The pro plugins version was...

**Comment by shiv19** [comment]
@kefahB 
I've fixed the issue that you were facing in the new PR :)

**Comment by kefahB** [comment]
Hey @shiv19 .. I have already ask Dave to merge [this PR](https://github.com/davecoffin/nativescript-filterable-listpicker/pull/53) to fixed it and Dave has merged .. but the current `2.2.6` version on npm dose not include this last change yet.

**Comment by davecoffin** [comment]
Hey @kefahB, shiva is working on a larger upgrade to the plugin that will bring it up to snuff with NativeScript 6, and that will include this.

**Pull request closed without merging**
