### PR TITLE
Add image caching capability

### PR DESCRIPTION
**Pull request by kefahB**
Hi @davecoffin, @shiv19,

I add image caching, on one of my project I had contact list with a lot of image, and for each load the image take a while time tp be reloaded [#38](https://github.com/davecoffin/nativescript-filterable-listpicker/issues/38#issue-379688033)... now there is no longer loading time issu, the first load will take a little, then all images will be cached.

To do test about caching please try to comment [this line](https://github.com/kefahB/nativescript-filterable-listpicker/blob/a7ffc3eec40f46aa95dc8f22bb64850cfe6ad87d/src/filterable-listpicker.ts#L117) and rebuild, try `Pick your favorite Animal` scroll to item 200 then close and reopen it, you will see how the image take à while te be reloaded on each open... uncomment it and will done ;-D

I did also a little `standard` for the `sources` property type, we can still bind an `Array` or `Object` on user side, but on the plugin side all item is typed as a `ObservableArray<SourceDataItem>`. 
```ts
if(typeof element === "object")
            unfilteredSource.push(new SourcesDataItem(element.title, element.image, element.description));
        else {
            console.log(element)
            unfilteredSource.push(new SourcesDataItem(element, null, null));
        }
```

### CODE REVIEW

**Comment by shiv19** [comment]
Thanks @kefahB you are awesome!

**Comment by kefahB** [comment]
May be we should discuss about typing all data to `ObservableArray` because this may will create an issus for user who will update the plugin ? since we add typing as `SourceDataItem` the returned item will be typed and for the users who bind a simple `Array` the result `item` will be `undefined`.. instead the result is : 
```ts
{
    title: "Title 1",
    image: null,
    description: null
}
```

We can put a warning on console ? what do you think @shiv19 @davecoffin  ?

**Comment by shiv19** [comment]
That's a good idea! something like this perhaps
```
export interface SourceData {
  title: string;
  image?: string;
  description?: string;
}
```

**Comment by kefahB** [comment]
Yes that what I already did  [here](https://github.com/kefahB/nativescript-filterable-listpicker/blob/7b6027f428eb7ca3bb54b85846649be2bec5af57/src/filterable-listpicker.ts#L383)😊 Actually I create a class that implements ´SourceDataItem’  interface .. The class is needed to set the image once it is downloaded and cached

**Comment by shiv19** [comment]
@davecoffin Can you please merge this :D

**Comment by davecoffin** [comment]
Sorry for the delay!

**Pull request merged**
